# -*- coding: utf-8 -*-
"""Assignment3.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1Y30ep7ptvJkd-A0cZaHDC1ucLv8sXY7r
"""

import matplotlib.pyplot as plt
import numpy as np
import math

x = np.linspace(-5,5,10000)
#Original lines
y_1 = (-2/3)*x+5/3 #straight line1
y_2 = 0.6*x+0.4 #straighe line2
plt.plot(x, y_1, label='2x+3y-5=0')
plt.plot(x, y_2, label='3x-5y+2=0')
#For affine transform
y_3=-np.sqrt(442)*np.sqrt(x**2-2*x+1)+21*x-20
y_4=np.sqrt(442)*np.sqrt(x**2-2*x+1)+21*x-20
plt.plot(x, y_3,color='green', label='obtuse bisector')
plt.plot(x, y_4,color='red', label='acute bisector')
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.xlim([-5,5])
plt.ylim([-5,5])
plt.grid()
plt.show()

#Modified pair of straight lines passing through origin
y_5 =0.5*x
y_6 =-0.5*x
plt.plot(x, y_5, label='2y=x')
plt.plot(x, y_6, label='2y=-x')
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid()
plt.show()
