# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y30ep7ptvJkd-A0cZaHDC1ucLv8sXY7r
"""

import matplotlib.pyplot as plt
import numpy as np
import math

x = np.linspace(-5,5,100)
#Original lines
y_1 = x-1 #straight line1
y_2 = 0.25*x+0.5 #straighe line2
plt.plot(x, y_1, label='x-y-1=0')
plt.plot(x, y_2, label='x-4y+2=0')
#For affine transform
y = np.linspace(-5,5,100)
x_1 = y*(-68-10*np.sqrt(34))/15 + 2
x_2 = 0*y + 1
plt.plot(x_1, y, label='x=-y(68+10*sqrt(34))/15 + 2')
plt.plot(x_2, y, label='x=1')
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.xlim([-5,5])
plt.ylim([-5,5])
plt.grid()
plt.show()

#Modified pair of straight lines passing through origin
y21 = (y*(np.sqrt(34) + 5))/3
y22 = (y*(-np.sqrt(34) - 5))/3
plt.plot(y, y21, label='y=x*(sqrt(34) + 5)/3')
plt.plot(y, y22, label='y=-x*(sqrt(34) + 5)/3')
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid()
plt.show()